import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';

import 'models/period.dart';
import 'screens/period_tracker_screen.dart';
import 'services/notification_service.dart';
import 'services/period_repository.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Hive must be initialized before opening boxes. Hive is not thread-safe.
  await Hive.initFlutter();

  // Register the adapter generated by build_runner in models/period.g.dart.
  // typeId must match the one in the @HiveType annotation on Period.
  if (!Hive.isAdapterRegistered(PeriodAdapter().typeId)) {
    Hive.registerAdapter(PeriodAdapter());
  }

  if (!Hive.isBoxOpen(PeriodRepository.boxName)) {
    await Hive.openBox<Period>(PeriodRepository.boxName);
  }

  // Initialize local notifications (idempotent). Safe to await before runApp;
  // iOS permission prompts can show after the first frame, which is fine.
  await NotificationService.instance.init();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MengaCloud Period Tracker',
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.purple,
          brightness: Brightness.light,
        ),
        scaffoldBackgroundColor: const Color(0xFFF5F7FA), // Light Nordic gray-white
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          foregroundColor: Colors.black87,
          elevation: 1,
        ),
      ),
      home: const PeriodTrackerScreen(),
    );
  }
}
